#!Dockerfile
# Auteur:   Alain Boudreault
# Date:     2025.12.21
# Solution: Laboratoire 5.7.1 de Dockerfile-Introduction
# -------------------------------------------------------------------------
# Création et activation, via ENV=, d'un fichier d'alias sous alpine
# docker build -f labo-5-7-1
# docker run -it --hostname labo5-7-1 labo-5-7-1
# -------------------------------------------------------------------------
FROM alpine

#set $ENV
ENV ENV=/etc/profile
#copy aliases definition

RUN { \
    echo "alias ll='ls -la'"; \
    echo "alias t='top'"; \
    echo "alias os='uname -a'"; \
    echo "alias c='clear'"; \
	} > /etc/profile.d/alias.sh
