#!Dockerfile
# Auteur:   Alain Boudreault
# Date:     2025.12.21
# -----------------------------------------------------------
# $ docker build --no-cache=true \
# --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
# --build-arg BUILD_VERSION=1.0 \
# -t mes-outils:latest \
# -f Dockerfile-labo-5.2 .
# -----------------------------------------------------------
# NOTE: The docker build --no-cache option forces Docker 
# to ignore all cached layers and rebuild the image entirely from scratch. 
# -----------------------------------------------------------

FROM alpine

# Labels
ARG BUILD_DATE
ARG BUILD_VERSION
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.build-date=${BUILD_DATE}
LABEL org.label-schema.version=${BUILD_VERSION:-1.0}
LABEL org.label-schema.docker.cmd="docker run --build-arg BUILD_DATE="" --build-arg BUILD_VERSION=1.0  mes-outils"
LABEL maintainer="dev@unprojet.org"

ENV DATE_DU_BUILD=${BUILD_DATE}

# COPY outils.tar.gz /mnt
# WORKDIR /mnt
# RUN tar zxvf /mnt/outils.tar.gz
# CMD ["/mnt/outils/outils.sh"]
CMD ["sh", "-c", "echo -e BUILD_DATE=$DATE_DU_BUILD"]
