# À vous de compléter le fichier
FROM php:8.0.3-apache-buster
LABEL   auteur="votre nom"
LABEL   email="yo@yo.yo"
# ---------- 

# Commande à exécuter au démarrage d'un conteneur
# Modifier la ligne suivante dans votre solution
CMD ["echo"," --------------------------\n","Je suis SuperMinou!\n","--------------------------\n"]